name: CI
on: [push, pull_request]

jobs:
  buildJob:
    name: Compile, test & Dockerize
    runs-on: ubuntu-latest
    env:
      PROJECTFOLDER: 'src/'
      ASSEMBLY_VERSION: '1.0.0'
      CONFIGURATION: Release
      BUILDDOCKER_CONDITION: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: dotnet restore
        run: dotnet restore $PROJECTFOLDER
      - name: dotnet build
        run: dotnet build $PROJECTFOLDER --configuration $CONFIGURATION /p:Version=$ASSEMBLY_VERSION --no-restore
      - name: dotnet test
        run: dotnet test $PROJECTFOLDER --configuration $CONFIGURATION --no-build
      - name: dotnet publish
        run: dotnet publish $PROJECTFOLDER --configuration $CONFIGURATION --no-build --output $GITHUB_WORKSPACE/publish/
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: files
          path: publish/
      - name: Docker Login
        if: $BUILDDOCKER_CONDITION
        uses: Azure/docker-login@v1
        with:
#          login-server: myregistry.azurecr.io 
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push Docker image
        if: $BUILDDOCKER_CONDITION
        env:
          DOCKERCONTEXT: 'publish/'
          DOCKERFILE: 'src/SimpleDockerfile'
          DOCKERIMAGE: 'anderslybecker/k8sfriendlyaspnetcore'
        run: |
          docker build $DOCKERCONTEXT -f $DOCKERFILE -t $DOCKERIMAGE:$ASSEMBLY_VERSION
          docker push $DOCKERIMAGE:$ASSEMBLY_VERSION
